<template>
  <div class="shuffler-container">
    <button class="pre" @click="shuffler.pre"><LeftOutlined /></button>
    <button class="next" @click="shuffler.next"><RightOutlined /></button>
    <div
      class="shuffler-images"
      :style="{
        width: sliderArray.length * 100 + '%',
        marginLeft: -shuffler.index * 100 + '%',
        display: 'flex',
        marginTop: '0px',
        transition: '0.5s',
      }"
    >
      <span
        v-for="(item, i) of sliderArray"
        :key="i"
        @mouseleave="shuffler.autoStart"
        @mouseenter="shuffler.autoStop"
      >
        <img :src="item" alt="" />
      </span>
    </div>
    <!-- 不知道为什么不起作用 -->
    <div class="action-dots">
      <div
        v-for="(item, ind) of sliderArray"
        :class="{ active: ind === shuffler.index }"
        :key="ind"
        @click="shuffler.index = ind"
      ></div>
    </div>
  </div>
</template>

<script>
import { defineComponent, ref, reactive, onMounted, toRefs } from "vue";
import { LeftOutlined, RightOutlined } from "@ant-design/icons-vue";
export default defineComponent({
  name: "Slider",
  props: {
    sliderArray: {
      require: true,
      type: Array,
    },
  },
  components: {
    LeftOutlined,
    RightOutlined,
  },
  setup(props) {
    var timerInt = null;
    var timeOut = null;

    const { sliderArray } = toRefs(props);

    function next() {
      shuffler.autoStop();
      shuffler.index = (shuffler.index + 1) % sliderArray.value.length;
      shuffler.autoStart();
    }

    function pre() {
      shuffler.autoStop();
      shuffler.index =
        (shuffler.index + sliderArray.value.length - 1) %
        sliderArray.value.length;
      shuffler.autoStart();
    }

    function autoStart() {
      if (!timerInt) {
        timerInt = setInterval(() => {
          shuffler.index = (shuffler.index + 1) % sliderArray.value.length;
        }, 6000);
      }
    }

    function autoStop() {
      clearInterval(timerInt);
      timerInt = null;
    }

    const shuffler = reactive({
      index: 0,
      autoStart: autoStart,
      autoStop: autoStop,
      next: next,
      pre: pre,
    });
    
    
    shuffler.autoStart();

    return {
      shuffler,
      sliderArray,
    };
  },
});
</script>

<style lang="scss" scoped>
.shuffler-container {
  position: relative;
  width: 100%;
  height: 100%;

  button {
    display: none;
    height: 40px;
    width: 40px;
    position: absolute;
    border: none;
    outline: none;
    border-radius: 50%;
    background: white;
    top: calc(50% - 20px);
    animation: fade-in 0.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
    cursor: pointer;
  }

  .pre {
    left: 30px;
  }

  .next {
    right: 30px;
  }

  &:hover {
    button {
      display: inline-block;
      transition: 0.3s; /** 不起作用 */
    }
  }

  .shuffler-images  {
    transition: 0.5s;
    display: flex;
    margin-top: 0;
  }

  .action-dots  {
    position: absolute;
    bottom: 10px;
    right: 10px;
    display: flex;

    div {
      width: 10px;
      height: 10px;
      cursor: pointer;
      margin: 0 3px;
      border-radius: 50%;
      border: 1px solid;
      color: #fff;
    }

    div.active  {
      background: #fff;
    }
  }
}

ul,
ol {
  padding-left: 0;
}

ul,
li {
  list-style: none;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-2-11 1:22:0
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

</style>